### ISSUE TITLE
API Post Relay

### ISSUE THREAD

**Issue by Aliceandsmith** [xiaoyang-sde/rocket-booster#264]
**Is your feature request related to a problem? Please describe.**
5 min got it working like a charm in Cloudflare, amazing. :) I don't know If I made a wrong configuration, but I don't seem to be able to pass any post data upstream.

**Describe the solution you'd like**
Catch the post body and relay it upstream

**Describe alternatives you've considered**
NGINX, it work but I would rather have it serverless.

**Additional context**
I want to add Cloudflare WAF and other features to a list of Azure API that I wish to limit the access. Some of these API are serverless features that have limited firewall capacity. I could also use Azure Frontdoor but cloudflare + rocket boost seem the best combination for smaller need.

**Comment by xiaoyang-sde** [comment]
Thank you for your request! I'm looking into that.

**Comment by Aliceandsmith** [comment]
The fact that you have a fully functional reverse proxy in Cloudflare is huge, you have no idea the impact this has on the Gaming Community with Microsoft PlayFab. I am not sure if this is related to the body that don't get forwarded or if it's the header that may no be forwarded. Here is the info you need:

**1) Setup a postman to test Microsoft API:**
https://docs.microsoft.com/en-us/gaming/playfab/sdks/postman/postman-quickstart

And use this to populate the API call inventory in Postman:
https://raw.githubusercontent.com/PlayFab/PostmanCollection/master/playfabV2.json

2) Make a call to Microsoft Playfab directly without going via the Reverse Proxy
- Navigate to the Client Group in Postman
- Choose LoginwithcustomID
- Use our test title to make a login:
https://92520.playfabapi.com/client/LoginWithCustomID?sdk=PostmanCollection-0.136.220118
- Set your body to JSON and pass the following Payload:
{
  "CustomId": "31337",
  "CreateAccount": false,
  "TitleId": "92520"
}

This will give you a session ticket / successful login flow.

3) Make a call via Cloudflare Worker / Rocket-Booster Reverse Proxy
- User our proxy route (change playfabapi for xrserver)
https://92520.xrserver.com/client/LoginWithCustomID?sdk=PostmanCollection-0.136.220118
- Send the call with the exact same body
- You should have a timeout

4) Test with no JSON body
- Still on our proxy, call the service with no API endpoint:
https://92520.xrserver.com/
- You will get the server status
- You will also get the same status by calling Microsoft API directly: https://92520.playfabapi.com/

5) Our current Reverse Proxy Configuration
import useProxy from 'rocket-booster';

addEventListener('fetch', (event) => {
  const proxy = useProxy();
  proxy.use('/*',{
      methods: ['GET', 'POST'],
      upstream: {
      domain: '92520.playfabapi.com',
      protocol: 'https',
    },
  });

  const response = proxy.apply(event.request);
  event.respondWith(response);
});
~

I can donate to the project if this can help to speed things up. :) Or anyway I can support you, let me know!

Thanks for your help! :)
Cheers!

**Comment by xiaoyang-sde** [comment]
I tested the endpoint with my own deployment (https://game.readme.workers.dev) with the following configuration:

```ts
import useProxy from 'rocket-booster';

addEventListener('fetch', (event) => {
  const proxy = useProxy();
  proxy.use('/', {
    methods: ['GET', 'POST'],
    upstream: {
    domain: '92520.playfabapi.com',
    protocol: 'https',
    },
  });

  const response = proxy.apply(event.request);
  event.respondWith(response);
});
```

I sent a POST request to https://game.readme.workers.dev/client/LoginWithCustomID?sdk=PostmanCollection-0.137.220131 with the following payload:
```json
{
    "CustomId": "31337",
    "CreateAccount": false,
    "TitleId": "92520"
}
```

and then I received this reply:
```json
{
    "code": 200,
    "status": "OK",
    "data": {
        "SessionTicket": "3F652CEA5365F636--4C6-92520-8D9EA6B619C1B50-/+KTheESQvE2qGiSbWGEEr8nTrZSdTp6IyDs1tjHOHs=",
        "PlayFabId": "3F652CEA5365F636",
        "NewlyCreated": false,
        "SettingsForUser": {
            "NeedsAttribution": false,
            "GatherDeviceInfo": true,
            "GatherFocusInfo": true
        },
        "LastLoginTime": "2022-02-07T18:55:12.008Z",
        "EntityToken": {
            "EntityToken": "NHxXWVpPbEJwZlZrVXRFTmVaRloxMHJtYjVoVnB2a0NCWWJLNWFvREpWcUpBPXx7ImkiOiIyMDIyLTAyLTA3VDE4OjU1OjE2Ljk2NTY2NTZaIiwiaWRwIjoiQ3VzdG9tIiwiZSI6IjIwMjItMDItMDhUMTg6NTU6MTYuOTY1NjY1NloiLCJ0aWQiOiJkZTc2M2MyNTgxOGY0MmNmYjc1NzUzNjk4MDBjYTFkNiIsImlkaSI6IjMxMzM3IiwiaCI6IjYwMjMyMzZEQzhBNzk1NSIsImVjIjoidGl0bGVfcGxheWVyX2FjY291bnQhOUIyMzY0ODBEOEM2RjU0MS85MjUyMC8zRjY1MkNFQTUzNjVGNjM2LzM4QjBBQUY5QzZBRjc5NC8iLCJlaSI6IjM4QjBBQUY5QzZBRjc5NCIsImV0IjoidGl0bGVfcGxheWVyX2FjY291bnQifQ==",
            "TokenExpiration": "2022-02-08T18:55:16.965Z",
            "Entity": {
                "Id": "38B0AAF9C6AF794",
                "Type": "title_player_account",
                "TypeString": "title_player_account"
            }
        },
        "TreatmentAssignment": {
            "Variants": [],
            "Variables": []
        }
    }
}
```

**Comment by xiaoyang-sde** [comment]
<img width="1095" alt="Screen Shot 2022-02-07 at 11 08 55" src="https://user-images.githubusercontent.com/13134143/152855285-51c67a3a-574e-49bc-8379-5351e61d3d0f.png">

Please check your HTTP route configuration. The error you encountered might happen because user forget to include `/*` in their route.

**Comment by Aliceandsmith** [comment]
And it works!!! I think the /* was the issues all along. :) Thank you so much for your time! I'll sure pass that along to the PlayFab community and give you credits! :)
