### ISSUE TITLE
Feature Request: replace_dict

### ISSUE THREAD

**Issue by 410679113** [xiaoyang-sde/rocket-booster#52]
**In the booster.js how to replace absolute links  domain in html ？** 

**In workers-proxy.js  we can use is fuction can change absolute links in html:**

```
const replace_dict = {
    '$upstream': '$custom_domain',
    '': ''
}
```

**Comment by xiaoyang-liu-cs** [comment]
Oh I haven't implemented that feature in booster.js yet. You could use the previous version: https://github.com/xiaoyang-liu-cs/booster.js/blob/4b924f286664af52cd4179919c5b86988850125a/src/index.js
